{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aps-gateway-allow-traffic-{{ include "bcbox.fullname" . }}-app
  labels:
    {{- include "bcbox.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: 264e6f
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: 264e6f
        - namespaceSelector:
            matchLabels:
              environment: test
              name: b8840c
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: b8840c
        - podSelector:
            matchLabels: {{ include "bcbox.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ default "8080" .Values.config.configMap.SERVER_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels: {{- include "bcbox.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
